import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'game.freezed.dart';
// optional: Since our Game class is serializable, we must add this line.
// But if Game was not serializable, we could skip it.
part 'game.g.dart';

@freezed
class Game with _$Game {
  const factory Game({
    required String name,
    required Map<int, int> tileMap,
    required int score,
  }) = _Game;

  factory Game.fromJson(Map<String, Object?> json) => _$GameFromJson(json);
}
